[project]
name = "sales-analysis-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "mcp[cli]>=1.10.1",
]

[project.scripts]
sales-analysis-mcp = "sales_analysis.__main__:main"
